project:
  type: book
  output-dir: .
  output-file: "Thesis"

book:
  title: El efecto de la pandemia del COVID-19 en las condiciones de vida de las familias de trabajadores del sector informal en el Perú urbano
  author:
    - name: Sotelo Galindo, Santiago Salvador
      url: http://www.google.com
  supervisor: 
    name: Sulmont, David
    url: http://www.google.com
  degree-name: Licenciado en Sociología
  # cover-image: D:/OneDrive - Universidad del Pacífico/quarto scripts/pucp-tesis/images/logo.pdf # ? no funciona
  # university: Pontificia Universidad Católica del Perú #quitar esto
  department: Department of Mathematics #?
  group: Informatics Program # ?
  faculty: Facultad de Ciencias Sociales
  city: Lima
  dateyear: 2022
  keywords: capital social, desigualdad

  acknowledgements: "Frontmatter/acknowledgements.tex"
  abstract: | 
    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam quis 
    accumsan ante. Quisque lorem metus, varius id urna eget, lacinia dapibus 
    sem. Etiam laoreet, quam ac mollis congue, arcu leo dictum neque, nec 
    euismod sem enim luctus odio. Donec condimentum tortor sit amet mollis 
    volutpat.
    
  abbreviations: "Frontmatter/abbreviations.tex"
  symbols: "Frontmatter/symbols.tex"
  dedication: "Frontmatter/dedication.tex"
  constants: "Frontmatter/constants.tex"
  chapters:
    - index.qmd
    - Chapters/Chapter2.qmd
    - Chapters/Chapter3.qmd
    - references.qmd
  appendices:
    - Appendices/AppendixA.qmd

bibliography: [example.bib]
# biblio-style: |
#   \newlength{\bibitemsep}\setlength{\bibitemsep}{.2\baselineskip plus .05\baselineskip minus .05\baselineskip}
#   \newlength{\bibparskip}\setlength{\bibparskip}{0pt}
#   \let\oldthebibliography\thebibliography
#   \renewcommand\thebibliography[1]{%
#     \oldthebibliography{#1}%
#     \setlength{\parskip}{\bibitemsep}%
#     \setlength{\itemsep}{\bibparskip}%
#   }


execute:
  echo: false
  code-overflow: wrap

lang: es

format:
  quarto-thesis-pdf:
    toc-depth: 2

